---

- name: Check user
  set_fact:
    user: "{{ ansible_ssh_user }}"
  when: user is undefined

- name: Check group
  set_fact: group={{ user }}
  when: group is undefined

- name: Set env_script_file fact
  set_fact:
    env_script_file: "{{ package_name }}.sh"

- name: Add a {{ group }} group for linux
  group: name={{ group }}

- name: Add a {{ user }} user for linux
  user: name={{ user }} group={{ group }}

- name: Change golang install dir ownership, group and mode for linux
  file: path={{ pkg_other_info.install_dir }}/{{ pkg_info.dir }} owner={{ user }} group={{ group }} mode=0755 recurse=true

- name: Setup the environment for linux
  template: src={{ env_script_file }} dest=/etc/profile.d/{{ env_script_file }}

- name: Change {{ env_script_file }} script ownership, group and mode for linux
  file: path=/etc/profile.d/{{ env_script_file }} owner={{ user }} group={{ group }} mode=0644

