---

- name: Gather package info facts for {{ os_family }}
  set_fact:
    pkg_info: "{{ maven_packages[package_version] }}"

- name: Gather package other info facts for {{ os_family }}
  set_fact:
    pkg_other_info: "{{ pkg_info[os_family] }}"