---

- include: package-common.yml

- name: Check and create install and temp directory in {{ ansible_distribution }} by pull install
  win_file: path={{ item }} state=directory
  with_items:
    # - "{{ pkg_other_info.install_dir }}"
    - "{{ pkg_other_info.download_dir }}"
  
- name: Download package in {{ ansible_distribution }} by pull install
  win_get_url: url={{ pkg_other_info.pull }} dest={{ pkg_other_info.download_dir }}/{{ pkg_other_info.file }}

- name: Install {{ package_name }} in {{ ansible_distribution }} by pull install
  win_chocolatey: name={{ package_name }}.install source={{ pkg_other_info.download_dir }} state=present

- name: Remove install package in {{ ansible_distribution }} by pull install
  win_file: path={{ pkg_other_info.download_dir }}/{{ pkg_other_info.file }} state=absent